### ISSUE TITLE
Recurring Poll

### ISSUE THREAD

**Issue by bio-boris** [KazuAlex/openpollslack#11]
@KazuAlex  Thank you for making this project open source!
Is it possible to make the poll reoccur daily at a specific time?
Thanks!

**Comment by KazuAlex** [comment]
Hey @bio-boris 

It's not possible server-side. I do not keep any data, sorry

**Comment by Khord** [comment]
With the (since new) Slack workflows feature, recurrence would be possible bymaking openpoll callable by workflows, similar to [simple poll](https://slack.com/slack-tips/speed-up-poll-creation-with-simple-poll). The scheduling and form content would be controlled by the workflow so you would not have to store any data.

**Comment by KazuAlex** [comment]
Can't test it but thank you @Khord 
Can see new section on help page to help users : https://github.com/KazuAlex/openpollslack/releases/tag/2.5.8

**Comment by Khord** [comment]
I believe something has to be programmed to present the user with a workflow "step" and send the relevant information to the bot. Essentially, with simple poll, the workflow step performs the equivalent action of a user running a slash command, but the Slack workflow is actuating it. 

See screenshots and this [link](https://simspace.slack.com/apps/collection/workflows)

[workflow steps api 
](https://api.slack.com/scopes/workflow.steps:execute)
![image](https://user-images.githubusercontent.com/21085666/146816769-0d4a9297-eafa-4253-b2f0-535227f31c6a.png)
![image](https://user-images.githubusercontent.com/21085666/146816894-96df53ca-cb5e-4cbc-b0f6-6442e47688ef.png)
![image](https://user-images.githubusercontent.com/21085666/146817490-42fcfe99-7711-4453-ab3c-6a3abcf21b3d.png)

**Comment by KazuAlex** [comment]
Workflow is a paid feature. I've not paid for. And I will not :(
Slack need to give access to their paid features to developers but don't... or I've not found how to access to it.
Slack don't care about "small" plugins developpers so I've not ask to have a "free paid plan" because support is really shitty.
I will contact them to have more information about a potential free "paid plan" for my development slack workspace.
