### ISSUE TITLE
Warning message displayed when creating a poll

### ISSUE THREAD

**Issue by zkrige** [KazuAlex/openpollslack#14]
```
This app will be supported until December 4th, 2020. Please update to new one : https://openpoll.slack.alcor.space and remove current.
```
I get this message, despite having the latest version installed

**Comment by KazuAlex** [comment]
Hi,

Do you have removed the existing and installed the new one from this page : https://openpoll.slack.alcor.space ?
This is a new different app on slack directory. I can't update the old without break existing installation.

**Comment by zoidbergwill** [comment]
We tried updating and still seem to see it: https://gitlab.com/KazuAlex/openpollslack/-/issues/13

**Comment by KazuAlex** [comment]
I will take a look to this tonight, thanks for the report

**Comment by KazuAlex** [comment]
Like i say it on gitlab issue, i've solved the problem : The site redirect to old app installation.

You need to perform installation again ([you can click here](https://slack.com/oauth/v2/authorize?client_id=768246087712.1206830278000&scope=commands,chat:write,chat:write.public&state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbnN0YWxsT3B0aW9ucyI6eyJzY29wZXMiOlsiY29tbWFuZHMiLCJjaGF0OndyaXRlLnB1YmxpYyIsImNoYXQ6d3JpdGUiXX0sIm5vdyI6IjIwMjAtMDYtMTdUMjA6NTc6MjYuMzI1WiIsImlhdCI6MTU5MjQyNzQ0Nn0.ZmnhLDbqxYGf0SBjqb7PzBXIe0Ud_NQ2RrURg-4va_E)). Sorry for the inconvenience.

And be carefull, the new app use `/poll` command instead of `/openpoll` ;)

**Comment by zkrige** [comment]
Thank you so much @KazuAlex - I really appreciate your quick response and help with solving the problem

**Comment by KazuAlex** [comment]
I thank you for reporting the problem and very sorry for the issue.

Slack really took a lot of time to approve the new app despite my multiple messages. And unfortunately I forgot to update the link into my website.

I close this issue :)
