### ISSUE TITLE
feature request: don't render vote buttons for closed votes

### ISSUE THREAD

**Issue by gitmotte** [KazuAlex/openpollslack#37]
... Instead of disabled buttons with error Text 
"You can't change your votes on closed poll."

**Comment by KazuAlex** [comment]
Hey @gitmotte 
It's a good idea. But... can't. From the slack documentation : https://api.slack.com/reference/block-kit/block-elements#button
we cannot disable button, only remove it. But users will maybe don't understand "why i can't vote". For now, they receive a message "you can't because the poll is closed"

**Comment by gitmotte** [comment]
It would be best to remove it - when a poll is closed, this status is also displayed for all to see anyway. Of course you first have to conclude that closed polls no longer allow voting ...
