### ISSUE TITLE
Unable to create poll in multi person private channels

### ISSUE THREAD

**Issue by hmomkargit** [KazuAlex/openpollslack#50]
Hi,
We are using OpenPoll in our slack and we are not able to start a poll in one of the multi person private slack channels which is I am also part of. I see this message "Some of channels may not be visible to the bot. This may result by impossibility to create the poll". 
Please provide information on resolving this . 

Thanks !

**Comment by polppol** [comment]
Hi,
You can try add OpenPoll Bot to that channel too in order to create poll in private channel.

However if you didn't create chanel but just a group of people in DM
 from my experience from summited my own fork version of OpenPoll to Slack App Dir.
Slack support team asking me to remove DM read permission from the app
as they dont like 3rd party app to read any private DM message.
So im not sure if by adding bot to your group chat will work or not.

If not only work arround is create new Private channel and adding people along with poll bot to that channel instead.

**Comment by hmomkargit** [comment]
Thanks ! It worked after after restarting the slack application.

**Comment by hmomkargit** [comment]
Closing
